using TMPro;
using UnityEngine;

namespace BlockPuzzle.Core
{
    /// <summary>Which Montserrat weight a text uses.</summary>
    public enum FontRole
    {
        /// <summary>Montserrat ExtraBold: titles, score numbers, button captions, prices.</summary>
        Heading,

        /// <summary>Montserrat SemiBold: hints, descriptions, captions, small print.</summary>
        Body
    }

    /// <summary>
    /// Loads the baked Montserrat TMP font assets from Resources. Both assets are generated by the
    /// editor tool (Tools/Block Puzzle/Ensure Montserrat TMP Fonts). When one is missing the text keeps
    /// TMP's default font, so a project that has not run the tool yet still renders.
    /// </summary>
    public static class GameFonts
    {
        public const string HeadingResource = "Fonts/Montserrat-ExtraBold SDF";
        public const string BodyResource = "Fonts/Montserrat-SemiBold SDF";

        private static TMP_FontAsset heading;
        private static TMP_FontAsset body;

        /// <summary>The font asset of <paramref name="role"/>; null when it has not been baked yet.</summary>
        public static TMP_FontAsset Get(FontRole role)
        {
            if (role == FontRole.Heading)
            {
                if (heading == null)
                {
                    heading = Resources.Load<TMP_FontAsset>(HeadingResource);
                }

                return heading;
            }

            if (body == null)
            {
                body = Resources.Load<TMP_FontAsset>(BodyResource);
            }

            return body;
        }

        /// <summary>Assigns the role's font (and its matching material) to <paramref name="text"/>.</summary>
        public static void Apply(TMP_Text text, FontRole role)
        {
            if (text == null)
            {
                return;
            }

            TMP_FontAsset font = Get(role);
            if (font != null)
            {
                text.font = font;
            }

            // The faces are already heavy; a synthetic bold on top only smears the counters.
            if ((text.fontStyle & FontStyles.Bold) != 0)
            {
                text.fontStyle &= ~FontStyles.Bold;
            }
        }

        /// <summary>True when <paramref name="font"/> is one of the two Montserrat assets.</summary>
        public static bool IsMontserrat(TMP_FontAsset font)
        {
            return font != null && font.name.StartsWith("Montserrat");
        }
    }
}
