using TMPro;
using UnityEngine;

namespace BlockPuzzle.Core
{
    /// <summary>Which Montserrat weight a text uses.</summary>
    public enum FontRole
    {
        /// <summary>Montserrat ExtraBold: titles, score numbers, button captions, prices.</summary>
        Heading,

        /// <summary>Montserrat SemiBold: hints, descriptions, captions, small print.</summary>
        Body
    }

    /// <summary>Baked material variant of a font: outline or drop shadow, set up in the editor, not in code.</summary>
    public enum FontPreset
    {
        /// <summary>The font's own material.</summary>
        None,

        /// <summary>Dark rim around the letters (OUTLINE_ON).</summary>
        Outline,

        /// <summary>Soft drop shadow (UNDERLAY_ON).</summary>
        Shadow
    }

    /// <summary>
    /// Loads the baked Montserrat TMP font assets from Resources. Both assets are generated by the
    /// editor tool (Tools/Block Puzzle/Ensure Montserrat TMP Fonts). When one is missing the text keeps
    /// TMP's default font, so a project that has not run the tool yet still renders.
    /// </summary>
    public static class GameFonts
    {
        public const string HeadingResource = "Fonts/Montserrat-ExtraBold SDF";
        public const string BodyResource = "Fonts/Montserrat-SemiBold SDF";

        private static TMP_FontAsset heading;
        private static TMP_FontAsset body;

        /// <summary>The font asset of <paramref name="role"/>; null when it has not been baked yet.</summary>
        public static TMP_FontAsset Get(FontRole role)
        {
            if (role == FontRole.Heading)
            {
                if (heading == null)
                {
                    heading = Resources.Load<TMP_FontAsset>(HeadingResource);
                }

                return heading;
            }

            if (body == null)
            {
                body = Resources.Load<TMP_FontAsset>(BodyResource);
            }

            return body;
        }

        /// <summary>Resource path of the baked material of <paramref name="role"/> in <paramref name="preset"/>.</summary>
        public static string PresetResource(FontRole role, FontPreset preset)
        {
            string font = role == FontRole.Heading ? HeadingResource : BodyResource;
            return font + " " + preset;
        }

        /// <summary>Assigns the role's font (and its matching material) to <paramref name="text"/>.</summary>
        public static void Apply(TMP_Text text, FontRole role)
        {
            Apply(text, role, FontPreset.None);
        }

        /// <summary>
        /// Assigns the role's font and, for a preset, the baked shared material of that preset. Never touches
        /// fontMaterial or the outline properties, so no material instance is created and nothing can throw
        /// on a text whose CanvasRenderer has not been initialised yet.
        /// </summary>
        public static void Apply(TMP_Text text, FontRole role, FontPreset preset)
        {
            if (text == null)
            {
                return;
            }

            TMP_FontAsset font = Get(role);
            if (font != null)
            {
                text.font = font;
            }

            // The faces are already heavy; a synthetic bold on top only smears the counters.
            if ((text.fontStyle & FontStyles.Bold) != 0)
            {
                text.fontStyle &= ~FontStyles.Bold;
            }

            if (preset == FontPreset.None || font == null)
            {
                return;
            }

            // A preset baked for another atlas would draw garbage; a missing one leaves the plain material.
            var material = Resources.Load<Material>(PresetResource(role, preset));
            if (material != null && material.mainTexture == font.atlasTexture)
            {
                text.fontSharedMaterial = material;
            }
        }

        /// <summary>True when <paramref name="font"/> is one of the two Montserrat assets.</summary>
        public static bool IsMontserrat(TMP_FontAsset font)
        {
            return font != null && font.name.StartsWith("Montserrat");
        }
    }
}
